Repository ChurchCRM/CRM, pull requests merged in 2018-02, with the labels that each got.

#3974 Apply fixes from StyleCI
  src/Menu.php
Labels: In Review

#3975 Self register cleanup
  src/ChurchCRM/model/ChurchCRM/Family.php
  src/ChurchCRM/model/ChurchCRM/Person.php
  src/ChurchCRM/model/ChurchCRM/User.php
  src/api/routes/families.php
  src/api/routes/groups.php
  src/api/routes/persons.php
  src/members/self-register.php
Labels: API, Feature: Members, In Review, bug

#3979 Postman export as 2.1 & Folder reorg
  postman/API/Database
  postman/API/Emails
  postman/API/Events
  postman/API/Persons
  postman/API/Public
  postman/API/Users
  postman/Database
  postman/Emails
  postman/Env/env.demo.churchcrm.io
  postman/Env/env.vagrantBox
  postman/Public
Labels: In Review

#3977 working login via post to get API Key
  src/api/index.php
  src/api/routes/public/public-user.php
Labels: In Review

#3978 Family view v2 updates
  src/ChurchCRM/model/ChurchCRM/Family.php
  src/FamilyView.php
  src/v2/templates/people/family-view.php
Labels: In Review

#3988 Apply fixes from StyleCI
  src/EventEditor.php
Labels: In Review

#3997 PostMan API Collection Cleanup
  postman/API/Database
  postman/API/Emails
  postman/API/Events
  postman/API/Persons
  postman/API/Users
  postman/Collections/Private API.postman_collection.json
  postman/Collections/Public API.postman_collection.json
  postman/Environments/env.demo.churchcrm.io
  postman/Environments/env.vagrantBox
Labels: In Review

#3907 New Calendar and Events
  demo/ChurchCRM-Database.sql
  propel/schema.xml
  src/ChurchCRM/Interfaces/SystemCalendar.php
  src/ChurchCRM/Slim/Middleware/AddEventsRoleAuthMiddleware.php
  src/ChurchCRM/SystemCalendars/AnniversariesCalendar.php
  src/ChurchCRM/SystemCalendars/BirthdaysCalendar.php
  src/ChurchCRM/dto/FullCalendarEvent.php
  src/ChurchCRM/dto/SystemCalendars.php
  src/ChurchCRM/dto/iCal.php
  src/ChurchCRM/model/ChurchCRM/CalendarEvent.php
  src/ChurchCRM/model/ChurchCRM/CalendarEventQuery.php
  src/ChurchCRM/model/ChurchCRM/Event.php
  src/ChurchCRM/model/ChurchCRM/EventType.php
  src/ChurchCRM/model/ChurchCRM/EventTypeQuery.php
  src/ChurchCRM/model/ChurchCRM/User.php
  src/ChurchCRM/utils/MiscUtils.php
  src/EventEditor.php
  src/Include/Header-function.php
  src/KioskManager.php
  src/api/index.php
  src/api/routes/calendar.php
  src/api/routes/events.php
  src/api/routes/public-calendar.php
  src/api/routes/public/public-calendar.php
  src/calendar.php
  src/composer.lock
  src/mysql/install/Install.sql
  src/mysql/upgrade.json
  src/mysql/upgrade/3.0.0.php
  src/mysql/upgrade/3.0.0.sql
  src/mysql/upgrade/rebuild_nav_menus.sql
  src/skin/js/CRMJSOM.js
  src/skin/js/Calendar.js
  src/v2/index.php
  src/v2/routes/calendar.php
  src/v2/templates/calendar/calendar.php
  tests/behat/features/Calendar/calendar.feature
  tests/composer.lock
Labels: In Review

#3992 Clear People and Families
  postman/Collections/Private API.postman_collection.json
  src/CSVImport.php
  src/ChurchCRM/FileSystemUtils.php
  src/ChurchCRM/dto/Photo.php
  src/api/routes/database.php
  src/skin/js/MemberView.js
Labels: In Review

#4006 Added a default API Key for Admin user
  demo/ChurchCRM-Database.sql
Labels: In Review, development

#4009 Code Reformat and import cleanup of API code
  src/api/index.php
  src/api/routes/calendar.php
  src/api/routes/cart.php
  src/api/routes/custom-fields.php
  src/api/routes/dashboard.php
  src/api/routes/database.php
  src/api/routes/deposits.php
  src/api/routes/email.php
  src/api/routes/events.php
  src/api/routes/families.php
  src/api/routes/geocoder.php
  src/api/routes/groups.php
  src/api/routes/issues.php
  src/api/routes/kiosks.php
  src/api/routes/persons.php
  src/api/routes/properties.php
  src/api/routes/public-data.php
  src/api/routes/public.php
  src/api/routes/public/public-calendar.php
  src/api/routes/register.php
  src/api/routes/roles.php
  src/api/routes/search.php
  src/api/routes/system.php
  src/api/routes/systemupgrade.php
  src/api/routes/users.php
Labels: Code Smell, In Review, development

#4008 moved send password reset link from external to public api
  postman/Collections/Public API.postman_collection.json
  src/api/routes/public/public-user.php
  src/external/routes/password.php
  src/external/templates/password/enter-username.php
Labels: Feature: Emails, Feature: Users, In Review

#4011 moved files into public API routes into a pubic dir
  src/api/index.php
  src/api/routes/public/public-data.php
  src/api/routes/public/public.php
Labels: In Review

#4010 convert constructors to use __construct
  src/Reports/ConfirmReport.php
  src/Reports/ConfirmReportEmail.php
  src/Reports/EnvelopeReport.php
  src/Reports/FRBidSheets.php
  src/Reports/FRCatalog.php
  src/Reports/FamilyPledgeSummary.php
  src/Reports/FundRaiserStatement.php
  src/Reports/PledgeSummary.php
  src/Reports/ReminderReport.php
  src/Reports/TaxReport.php
  src/Reports/VotingMembers.php
  src/Reports/ZeroGivers.php
Labels: In Review

#4014 Api docs cleanup
  postman/Collections/Private API.postman_collection.json
  src/api/index.php
  src/api/routes/calendar/calendar.php
  src/api/routes/calendar/events.php
  src/api/routes/finance/finance-deposits.php
  src/api/routes/finance/finance-payments.php
  src/api/routes/people/people-email.php
  src/api/routes/people/people-families.php
  src/api/routes/people/people-groups.php
  src/api/routes/people/people-persons.php
  src/api/routes/people/people-properties.php
  src/api/routes/people/people-roles.php
  src/api/routes/system/system-custom-fields.php
  src/api/routes/system/system-database.php
  src/api/routes/system/system-issues.php
  src/api/routes/system/system-register.php
  src/api/routes/system/system-timerjobs.php
  src/api/routes/system/system-upgrade.php
  src/api/routes/system/system.php
Labels: In Review

#4020 Added check to make sure per_Birthday and per_BirthMonth are greater than zero in PDF Church Directory
  src/ChurchCRM/Reports/PDF_Directory.php
Labels: In Review
