Repository ChurchCRM/CRM, pull requests merged in 2018-03, with the labels that each got.

#4016 Feature/4015 add new calendar
  postman/Collections/Private API.postman_collection.json
  src/api/routes/calendar/calendar.php
  src/mysql/install/Install.sql
  src/skin/churchcrm.scss
  src/skin/js/Calendar.js
  src/skin/scss/_calendars.scss
  src/skin/scss/_strike.scss
  src/v2/routes/calendar.php
  tests/behat/features/Calendar/calendar.feature
Labels: In Review

#4012 Starting ORM validation - Members
  propel/schema.xml
  src/ChurchCRM/utils/ORMUtils.php
Labels: In Review

#4049 Apply fixes from StyleCI
  src/ChurchCRM/SessionUser.php
Labels: In Review

#4039 System Menu v3
  demo/ChurchCRM-Database.sql
  locale/extract-db-locale-terms.php
  propel/schema.xml
  src/ChurchCRM/Config/Menu/Menu.php
  src/ChurchCRM/Config/Menu/MenuCounter.php
  src/ChurchCRM/Config/Menu/MenuItem.php
  src/ChurchCRM/Service/ReportingService.php
  src/ChurchCRM/Service/SystemService.php
  src/ChurchCRM/Service/UpgradeService.php
  src/ChurchCRM/SessionUser.php
  src/ChurchCRM/model/ChurchCRM/MenuConfig.php
  src/ChurchCRM/model/ChurchCRM/MenuConfigQuery.php
  src/ChurchCRM/model/ChurchCRM/User.php
  src/ChurchCRM/view/MenuRenderer.php
  src/FinancialReports.php
  src/Include/Header-function.php
  src/Include/Header.php
  src/ReportList.php
  src/mysql/install/Install.sql
  src/mysql/upgrade/3.0.0.sql
  src/mysql/upgrade/rebuild_nav_menus.sql
Labels: In Review

#4051 Demo data/finance
  demo/ChurchCRM-Database.sql
Labels: In Review

#4052 Enabled / Disable Menus Items
  src/ChurchCRM/Config/Menu/Menu.php
  src/ChurchCRM/dto/SystemConfig.php
Labels: In Review

#4053 Feature: Menu external links
  demo/ChurchCRM-Database.sql
  propel/schema.xml
  src/ChurchCRM/Config/Menu/Menu.php
  src/ChurchCRM/Config/Menu/MenuItem.php
  src/ChurchCRM/model/ChurchCRM/MenuLink.php
  src/ChurchCRM/model/ChurchCRM/MenuLinkQuery.php
  src/ChurchCRM/view/MenuRenderer.php
  src/api/index.php
  src/api/routes/system/system-custom-menu.php
  src/mysql/install/Install.sql
Labels: In Review

#4050 display correct age on "upcoming" birthday events"
  src/ChurchCRM/SystemCalendars/BirthdaysCalendar.php
  src/ChurchCRM/model/ChurchCRM/Person.php
Labels: In Review

#4057 3.0.0 Locale updates 3/4
  locale/JSONKeys/es_ES.json
  locale/JSONKeys/zh_TW.json
  locale/messages.po
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.mo
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.po
  src/locale/textdomain/zh_TW/LC_MESSAGES/messages.mo
  src/locale/textdomain/zh_TW/LC_MESSAGES/messages.po
Labels: In Review

#4058 Locale - 3.0.0 v3
  locale/JSONKeys/ar_EG.json
  locale/JSONKeys/de_DE.json
  locale/JSONKeys/es_ES.json
  locale/JSONKeys/fr_FR.json
  locale/JSONKeys/hu_HU.json
  locale/JSONKeys/id_ID.json
  locale/JSONKeys/it_IT.json
  locale/JSONKeys/nb_NO.json
  locale/JSONKeys/nl_NL.json
  locale/JSONKeys/pl_PL.json
  locale/JSONKeys/pt_BR.json
  locale/JSONKeys/ro_RO.json
  locale/JSONKeys/ru_RU.json
  locale/JSONKeys/sq_AL.json
  locale/JSONKeys/sv_SE.json
  locale/JSONKeys/vi_VN.json
  locale/JSONKeys/zh_CN.json
  locale/JSONKeys/zh_TW.json
  src/locale/textdomain/ar_EG/LC_MESSAGES/messages.mo
  src/locale/textdomain/ar_EG/LC_MESSAGES/messages.po
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.mo
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.po
  src/locale/textdomain/en_AU/LC_MESSAGES/messages.po
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.mo
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.po
  src/locale/textdomain/fr_FR/LC_MESSAGES/messages.mo
  src/locale/textdomain/fr_FR/LC_MESSAGES/messages.po
  src/locale/textdomain/hu_HU/LC_MESSAGES/messages.mo
  src/locale/textdomain/hu_HU/LC_MESSAGES/messages.po
  src/locale/textdomain/id_ID/LC_MESSAGES/messages.mo
  src/locale/textdomain/id_ID/LC_MESSAGES/messages.po
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.mo
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.po
  src/locale/textdomain/nb_NO/LC_MESSAGES/messages.mo
  src/locale/textdomain/nb_NO/LC_MESSAGES/messages.po
  src/locale/textdomain/nl_NL/LC_MESSAGES/messages.mo
  src/locale/textdomain/nl_NL/LC_MESSAGES/messages.po
  src/locale/textdomain/pl_PL/LC_MESSAGES/messages.mo
  src/locale/textdomain/pl_PL/LC_MESSAGES/messages.po
  src/locale/textdomain/pt_BR/LC_MESSAGES/messages.mo
  src/locale/textdomain/pt_BR/LC_MESSAGES/messages.po
  src/locale/textdomain/ro_RO/LC_MESSAGES/messages.mo
  src/locale/textdomain/ro_RO/LC_MESSAGES/messages.po
  src/locale/textdomain/ru_RU/LC_MESSAGES/messages.mo
  src/locale/textdomain/ru_RU/LC_MESSAGES/messages.po
  src/locale/textdomain/sq_AL/LC_MESSAGES/messages.mo
  src/locale/textdomain/sq_AL/LC_MESSAGES/messages.po
  src/locale/textdomain/sv_SE/LC_MESSAGES/messages.mo
  src/locale/textdomain/sv_SE/LC_MESSAGES/messages.po
  src/locale/textdomain/th_TH/LC_MESSAGES/messages.po
  src/locale/textdomain/vi_VN/LC_MESSAGES/messages.mo
  src/locale/textdomain/vi_VN/LC_MESSAGES/messages.po
  src/locale/textdomain/zh_CN/LC_MESSAGES/messages.mo
  src/locale/textdomain/zh_CN/LC_MESSAGES/messages.po
  src/locale/textdomain/zh_TW/LC_MESSAGES/messages.mo
  src/locale/textdomain/zh_TW/LC_MESSAGES/messages.po
Labels: In Review

#4060 updated simple pages
  src/composer.json
Labels: In Review

#4061 Codesmell/update phpmailer
  src/ChurchCRM/Emails/BaseEmail.php
  src/composer.json
  src/v2/routes/email.php
  src/v2/templates/email/dashboard.php
Labels: In Review

#4063 Footer 2018 update
  src/Include/Footer.php
Labels: In Review

#4064 3.0.0v4
  locale/messages.po
Labels: In Review

#4067 Apply fixes from StyleCI
  src/Include/Header-function.php
Labels: In Review

#4068 Apply fixes from StyleCI
  src/Login.php
Labels: In Review

#4072 Update FamilyView.php
  src/FamilyView.php
Labels: In Review

#4074 Apply fixes from StyleCI
  src/Include/LoadConfigs.php
Labels: In Review

#4071 Issue 4055 - Add support for MySQL on non-standard ports
  src/Include/Config.php.example
  src/Include/LoadConfigs.php
  src/setup/routes/setup.php
  src/setup/templates/setup-steps.php
Labels: In Review

#4075 Apply fixes from StyleCI
  src/Include/LoadConfigs.php
Labels: In Review

#4084 Apply fixes from StyleCI
  src/ChurchCRM/SQLUtils.php
Labels: In Review

#4085 Bugfix/misc 3.0.0 bugs
  src/ChurchCRM/SQLUtils.php
  src/ChurchCRM/Service/UpgradeService.php
  src/mysql/install/Install.sql
  src/mysql/upgrade.json
  src/mysql/upgrade/2.9.0-InnoDB.php
  src/mysql/upgrade/3.0.0.sql
Labels: In Review

#4059 Bugfix/js error modal
  src/Login.php
  src/skin/js/CRMJSOM.js
  src/skin/js/Footer.js
Labels: In Review

#4089 CodeSmell: import cleanup
  src/api/routes/public/public-user.php
  src/api/routes/system/system-custom-menu.php
Labels: In Review

#4090 Email dashboard: Dup Emails
  src/api/routes/people/people-email.php
  src/v2/routes/email.php
  src/v2/templates/email/dashboard.php
  src/v2/templates/email/duplicate.php
Labels: In Review

#4066 Notify alerts v1
  Gruntfile.js
  package.json
  src/Include/Header-HTML-Scripts.php
  src/Include/Header-function.php
  src/skin/scss/_SystemNotifications.scss
Labels: In Review, do not merge!

#4088 CodeSmell: RestfulAPIs: withStatus reason / codes
  src/ChurchCRM/Slim/Middleware/AuthMiddleware.php
  src/ChurchCRM/Slim/Middleware/PublicCalendarAPIMiddleware.php
  src/ChurchCRM/Slim/Middleware/Role/BaseAuthRoleMiddleware.php
  src/api/routes/calendar/calendar.php
  src/api/routes/calendar/events.php
  src/api/routes/geocoder.php
  src/api/routes/people/people-families.php
  src/api/routes/people/people-groups.php
  src/api/routes/people/people-persons.php
  src/api/routes/people/people-roles.php
  src/api/routes/public/public-user.php
  src/api/routes/system/system-custom-menu.php
  src/api/routes/users.php
  src/setup/routes/setup.php
  src/v2/routes/user.php
Labels: In Review

#4073 Calendar/add html public view
  src/ChurchCRM/Slim/Middleware/PublicCalendarAPIMiddleware.php
  src/api/routes/public/public-calendar.php
  src/external/index.php
  src/external/routes/calendar.php
  src/external/templates/calendar/calendar.php
  src/skin/js/Calendar.js
Labels: In Review

#4101 last locale-gen pre 3.0.0rc
  locale/JSONKeys/it_IT.json
  locale/messages.po
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.po
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.po
  src/locale/textdomain/fr_FR/LC_MESSAGES/messages.po
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.mo
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.po
  src/locale/textdomain/pt_BR/LC_MESSAGES/messages.po
  src/locale/textdomain/vi_VN/LC_MESSAGES/messages.po
Labels: In Review

#4105 Apply fixes from StyleCI
  src/Include/Footer.php
Labels: In Review

#4104 Moving Menus from Right Nav to Admin Menus on Right Nav
  src/ChurchCRM/Config/Menu/Menu.php
  src/ChurchCRM/view/MenuRenderer.php
  src/Include/Footer.php
  src/Include/Header.php
Labels: In Review

#4100 closes #4099
  src/ChurchCRM/Slim/Middleware/AuthMiddleware.php
Labels: In Review

#4108 Fix Update Admin change User Password #4107
  src/UserPasswordChange.php
Labels: In Review

#4109 use new GH url for notifications.json
  src/ChurchCRM/Service/NotificationService.php
  src/ChurchCRM/dto/SystemConfig.php
Labels: In Review

#4116 Twitter poll is now closed
  notifications.json
Labels: In Review

#4120 using notify in showGlobalMessage
  src/Include/Header.php
  src/skin/js/Footer.js
Labels: In Review

#4114 Feature: Notification v2
  src/ChurchCRM/Service/SystemService.php
  src/ChurchCRM/Service/TaskService.php
  src/ChurchCRM/Slim/Middleware/AuthMiddleware.php
  src/ChurchCRM/dto/Notification/UiNotification.php
  src/GroupList.php
  src/Include/Footer.php
  src/Include/Header-HTML-Scripts.php
  src/Include/Header-function.php
  src/Include/Header.php
  src/api/routes/system/system.php
  src/skin/js/Footer.js
  tests/behat/features/Groups/GroupsList.feature
Labels: In Review

#4119 fix links for birthdays and anniversaries closes #4110
  demo/ChurchCRM-Database.sql
  propel/schema.xml
  src/ChurchCRM/SystemCalendars/AnniversariesCalendar.php
  src/ChurchCRM/SystemCalendars/BirthdaysCalendar.php
  src/ChurchCRM/dto/FullCalendarEvent.php
  src/mysql/install/Install.sql
  src/mysql/upgrade/3.0.0.sql
Labels: Feature: Events, In Review

#4076 Bugfix/4055 support mysql nonstandard port
  src/Include/LoadConfigs.php
Labels: In Review

#4097 Middleware cleanup - role name space
  src/ChurchCRM/Slim/Middleware/Role/AddEventsRoleAuthMiddleware.php
  src/ChurchCRM/Slim/Middleware/Role/AdminRoleAuthMiddleware.php
  src/ChurchCRM/Slim/Middleware/Role/DeleteRecordRoleAuthMiddleware.php
  src/ChurchCRM/Slim/Middleware/Role/MenuOptionsRoleAuthMiddleware.php
  src/api/routes/calendar/calendar.php
  src/api/routes/calendar/events.php
  src/api/routes/people/people-properties.php
  src/api/routes/system/system-custom-fields.php
  src/api/routes/system/system-custom-menu.php
  src/api/routes/system/system-database.php
  src/api/routes/users.php
  src/v2/routes/email.php
  src/v2/routes/user.php
Labels: In Review

#4122 Postman/3.0.0v1
  postman/Collections/Private API.postman_collection.json
  postman/Collections/Public API.postman_collection.json
Labels: In Review

#4124 Locale/3.0.0v7
  locale/JSONKeys/de_DE.json
  locale/JSONKeys/es_ES.json
  locale/JSONKeys/fr_FR.json
  locale/JSONKeys/it_IT.json
  locale/JSONKeys/pt_BR.json
  locale/JSONKeys/vi_VN.json
  locale/JSONKeys/zh_TW.json
  locale/messages.po
  src/locale/textdomain/ar_EG/LC_MESSAGES/messages.po
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.mo
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.po
  src/locale/textdomain/en_AU/LC_MESSAGES/messages.po
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.mo
  src/locale/textdomain/es_ES/LC_MESSAGES/messages.po
  src/locale/textdomain/fr_FR/LC_MESSAGES/messages.mo
  src/locale/textdomain/fr_FR/LC_MESSAGES/messages.po
  src/locale/textdomain/hu_HU/LC_MESSAGES/messages.po
  src/locale/textdomain/id_ID/LC_MESSAGES/messages.po
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.mo
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.po
  src/locale/textdomain/nb_NO/LC_MESSAGES/messages.po
  src/locale/textdomain/nl_NL/LC_MESSAGES/messages.po
  src/locale/textdomain/pl_PL/LC_MESSAGES/messages.po
  src/locale/textdomain/pt_BR/LC_MESSAGES/messages.mo
  src/locale/textdomain/pt_BR/LC_MESSAGES/messages.po
  src/locale/textdomain/ro_RO/LC_MESSAGES/messages.po
  src/locale/textdomain/ru_RU/LC_MESSAGES/messages.po
  src/locale/textdomain/sq_AL/LC_MESSAGES/messages.po
  src/locale/textdomain/sv_SE/LC_MESSAGES/messages.po
  src/locale/textdomain/th_TH/LC_MESSAGES/messages.po
  src/locale/textdomain/vi_VN/LC_MESSAGES/messages.mo
  src/locale/textdomain/vi_VN/LC_MESSAGES/messages.po
  src/locale/textdomain/zh_CN/LC_MESSAGES/messages.po
  src/locale/textdomain/zh_TW/LC_MESSAGES/messages.mo
  src/locale/textdomain/zh_TW/LC_MESSAGES/messages.po
Labels: In Review

#4123 Fixed API login issues
  src/ChurchCRM/Slim/Middleware/AuthMiddleware.php
Labels: In Review

#4131 Fix API Event Sort By Date
  src/ChurchCRM/Slim/Middleware/PublicCalendarAPIMiddleware.php
Labels: In Review

#4132 Use calendar name as page title
  src/external/templates/calendar/calendar.php
Labels: In Review

#4142 Travis Testing on php 7.2
  .travis.yml
Labels: In Review

#4146 Apply fixes from StyleCI
  src/Include/Header-function.php
Labels: In Review

#4150 Maps Bugs
  src/skin/js/CRMJSOM.js
Labels: In Review

#4154 debug system URLs
  postman/Collections/Private API.postman_collection.json
  src/api/index.php
  src/api/routes/system/system-debug.php
Labels: In Review

#4153 fixed session login 404/500 error
  src/ChurchCRM/utils/RedirectUtils.php
Labels: In Review

#4147 CodeSmell: Api/background cleanup
  src/ChurchCRM/Service/SystemService.php
  src/ChurchCRM/Slim/Middleware/AuthMiddleware.php
  src/Include/Header-Security.php
  src/api/index.php
  src/api/routes/background.php
  src/api/routes/dashboard.php
  src/api/routes/system/system-database.php
  src/api/routes/system/system-timerjobs.php
  src/api/routes/system/system.php
  src/skin/js/CRMJSOM.js
Labels: In Review

#4143 Dashboard Person #3822
  src/ChurchCRM/Service/DashboardService.php
  src/Menu.php
Labels: In Review

#4176 Bug/cart add person
  src/CSVCreateFile.php
  src/Include/Functions.php
  src/api/routes/people/people-persons.php
Labels: In Review

#4145 Security: Menus and User config Permission
  demo/ChurchCRM-Database.sql
  src/CSVExport.php
  src/CartView.php
  src/ChurchCRM/Config/Menu/Menu.php
  src/ChurchCRM/Config/Menu/MenuItem.php
  src/ChurchCRM/model/ChurchCRM/User.php
  src/ChurchCRM/utils/RedirectUtils.php
  src/FamilyEditor.php
  src/Include/Header-function.php
  src/PropertyTypeList.php
  src/UserList.php
  src/api/routes/users.php
  src/mysql/install/Install.sql
Labels: In Review

#4178 update composer dependencies
  src/composer.lock
Labels: In Review

#4179 3.0.1 - locale-download 3/39
  locale/JSONKeys/de_DE.json
  locale/JSONKeys/id_ID.json
  locale/JSONKeys/it_IT.json
  locale/JSONKeys/nl_NL.json
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.mo
  src/locale/textdomain/de_DE/LC_MESSAGES/messages.po
  src/locale/textdomain/id_ID/LC_MESSAGES/messages.mo
  src/locale/textdomain/id_ID/LC_MESSAGES/messages.po
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.mo
  src/locale/textdomain/it_IT/LC_MESSAGES/messages.po
  src/locale/textdomain/nl_NL/LC_MESSAGES/messages.mo
  src/locale/textdomain/nl_NL/LC_MESSAGES/messages.po
Labels: In Review

#4187 Fix auto upgrade to 3.0.2
  notifications.json
Labels: In Review

#4191 Apply fixes from StyleCI
  .gitignore
Labels: In Review

#4190 Build/3.0.3
  demo/ChurchCRM-Database.sql
  locale/messages.po
  package.json
  src/composer.json
  src/mysql/upgrade.json
Labels: In Review

#4189 Api: Person/Persons Code Cleanup - Part 1
  postman/Collections/Private API.postman_collection.json
  src/ChurchCRM/Slim/Middleware/Helper/PersonAPIMiddleware.php
  src/ChurchCRM/Slim/Middleware/Role/EditRecordsRoleAuthMiddleware.php
  src/api/index.php
  src/api/routes/people/people-email.php
  src/api/routes/people/people-person.php
  src/api/routes/people/people-persons.php
  src/api/routes/people/people-roles.php
  src/skin/js/PersonView.js
Labels: In Review
