Repository ChurchCRM/CRM, pull requests merged in 2021-04, with the labels that each got.

#5730 Bigfix/person edit fb
  package-lock.json
  package.json
  src/PersonEditor.php
Labels: Integration Testing, bug

#5728 Bugfix: Display custom drop-down option name in Family metadata view
  demo/ChurchCRM-Database.sql
  src/ChurchCRM/dto/PeopleCustomField.php
Labels: Feature: Members

#5734 Tests/fix flaky integration tests
  cypress/integration/ui/finance/finance.family.spec.js
  cypress/integration/ui/standard/standard.cart.spec.js
  cypress/integration/ui/standard/standard.family.spec.js
  docker/cypress.json
  src/ChurchCRM/Authentication/AuthenticationManager.php
  src/ChurchCRM/Bootstrapper.php
  src/ChurchCRM/Service/ReportingService.php
  src/ChurchCRM/Service/SystemService.php
  src/api/dependencies.php
  src/api/routes/finance/finance-payments.php
  src/external/dependencies.php
  src/external/index.php
Labels: Integration Testing

#5735 Bugfix: Add birthdate validation on data entry and CSV export
  src/CSVCreateFile.php
  src/FamilyEditor.php
  src/PersonEditor.php
Labels: Feature: Data Import / Export

#5741 Starting 4.4.1
  CODEOWNERS
  demo/ChurchCRM-Database.sql
  locale/messages.po
  package-lock.json
  package.json
  src/composer.json
  src/composer.lock
  src/mysql/upgrade.json
Labels: build
