Repository ChurchCRM/CRM, pull requests merged in 2022-12, with the labels that each got.

#6093 Add $delimiter instead of hardcoded commas
  src/CSVCreateFile.php
Labels: Feature: Data Import / Export

#6115 Bug: replaced bg-aqua to bg-gray
  src/PeopleDashboard.php
  src/PersonView.php
  src/sundayschool/SundaySchoolDashboard.php
Labels: bug, UI

#6116 fixed API call to delete user
  src/api/routes/users/user-admin.php
  src/skin/js/users.js
Labels: Feature: Users, UI, API

#6117 Fixed new system setup error in 4.5.0
  src/ChurchCRM/dto/SystemConfig.php
Labels: bug, Installation / Upgrade

#6125 Bug: Fixed method call for family getSalutation
  src/ChurchCRM/Reports/ChurchInfoReport.php
  src/MapUsingGoogle.php
Labels: bug
