Repository ChurchCRM/CRM, pull requests merged in 2023-11, with the labels that each got.

#6604 Build: 5.1.0
  demo/ChurchCRM-Database.sql
  package-lock.json
  package.json
  src/composer.json
  src/mysql/upgrade.json
  src/mysql/upgrade/5.1.0.sql
Labels: build

#6605 Remove System regestration feature
  src/ChurchCRM/Service/TaskService.php
  src/ChurchCRM/tasks/RegisteredTask.php
  src/Register.php
  src/mysql/upgrade/5.1.0.sql
Labels: Code Smell

#6609 Moved from Custom github action for Release Notes to github builtin
  .github/release.yml
Labels: build

#6618 enable ORM logs only if we are in debug mode
  src/ChurchCRM/Bootstrapper.php
Labels: Security

#6616 Fixed Issue Reporting
  cypress/e2e/ui/user/standard.user.report-issue.spec.js
  locale/messages.po
  src/ChurchCRM/Service/SystemService.php
  src/Include/Header-function.php
  src/Include/Header.php
  src/api/routes/system/system-issues.php
  src/skin/js/IssueReporter.js
Labels: bug

#6617 Bug: Fix Event Checkin
  cypress/e2e/ui/events/standard.events.spec.js
  src/Checkin.php
Labels: bug

#6620 5.1.1 - Build Script Cleanup
  CHANGELOG.md
  Gruntfile.js
  demo/ChurchCRM-Database.sql
  package.json
  scripts/startNewRelease.py
  scripts/update-demo-site.php
  src/composer.json
  src/mysql/upgrade.json
Labels: build

#6625 Bug Fixes & Cleanup 5.1.1
  cypress/e2e/ui/finance/finance.deplosits.spec.js
  demo/ChurchCRM-Database.sql
  src/CSVCreateFile.php
  src/ChurchCRM/dto/Photo.php
  src/ChurchCRM/dto/SystemConfig.php
  src/ChurchCRM/utils/MiscUtils.php
  src/GroupView.php
  src/PledgeEditor.php
  src/PrintView.php
  src/Reports/CanvassReports.php
  src/Reports/ClassAttendance.php
  src/Reports/ClassList.php
  src/UserList.php
  src/api/routes/people/people-groups.php
  src/setup/routes/setup.php
  src/skin/js/DepositSlipEditor.js
  src/skin/js/FindDepositSlip.js
  src/sundayschool/SundaySchoolClassListExport.php
  src/sundayschool/SundaySchoolClassView.php
  src/sundayschool/SundaySchoolDashboard.php
  src/v2/templates/cart/cartfunctions.php
  src/v2/templates/people/family-view.php
Labels: bug

#6624 Development Updates: GitHub Templates & Scripts
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  docker/nginx/default.conf
  package.json
  scripts/restore-db.php
Labels: development

#6627 attempt to fix potentially-undefined fn apache_get_modules, only allow upgrade when logged in, fix kiosk routes, misc minor cleanup
  src/ChurchCRM/Authentication/AuthenticationManager.php
  src/ChurchCRM/Authentication/AuthenticationProviders/APITokenAuthentication.php
  src/ChurchCRM/Authentication/AuthenticationProviders/LocalAuthentication.php
  src/ChurchCRM/Service/AppIntegrityService.php
  src/UpgradeCRM.php
  src/kiosk/index.php
  src/session/index.php
Labels: bug

#6630 Upgrade frontend deps
  Gruntfile.js
  cypress/e2e/ui/events/standard.calendar.spec.js
  package-lock.json
  package.json
  react/calendar-event-editor.tsx
  src/ChurchCRM/dto/FullCalendarEvent.php
  src/Include/Footer.php
  src/api/routes/calendar/calendar.php
  src/external/templates/calendar/calendar.php
  src/locale/locales.json
  src/skin/churchcrm.scss
  src/skin/js/Calendar.js
Labels: Feature: Events / Calendar, Package Dependencies, javascript

#6650 UI: Bug Fix - Left Nav Bar
  src/ChurchCRM/view/MenuRenderer.php
Labels: bug

#6648 StyleCI now uses .styleci.yml
  .styleci.yml
Labels: development

#6654 fix error when updating Family
  src/ChurchCRM/dto/Photo.php
Labels: php

#6652 allow for empty birthday when initially inputting person
  src/PersonEditor.php
Labels: Feature: Users, php

#6667 add debug step request to bug issue, comment out user prompts
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#6665 fix adding group roles by properly retrieving required service from the container
  src/api/routes/finance/finance-payments.php
  src/api/routes/people/people-groups.php
Labels: bug, php

#6661 UI Bugs: PDF Labels & Group to Cart
  src/Reports/PDFLabel.php
  src/skin/js/GroupList.js
Labels: enhancement, UI, javascript

#6675 Fix sunday school page bug
  src/ChurchCRM/Service/SundaySchoolService.php
  src/sundayschool/SundaySchoolClassView.php
  src/sundayschool/SundaySchoolDashboard.php
Labels: bug, Feature: Sunday School, php

#6668 fix error in /api/families/updated
  src/api/routes/people/people-families.php
Labels: bug, API, php

#6676 Starting 5.2.3
  demo/ChurchCRM-Database.sql
  package-lock.json
  package.json
  src/composer.json
  src/composer.lock
  src/mysql/upgrade.json
Labels: build

#6677 Update README.md
  README.md
Labels: Documentation

#6680 Fix sunday school graphs
  Gruntfile.js
  src/sundayschool/SundaySchoolClassView.php
Labels: bug, build, Feature: Sunday School, javascript

#6679 make build faster by running things in parallel, switch release to node script for consistency
  package-lock.json
  package.json
  scripts/startNewRelease.js
  scripts/startNewRelease.py
Labels: build

#6682 tell user what version of php they're running for quality of life
  src/index.php
  src/php-error.html
Labels: Installation / Upgrade, php

#6683 No Longer Support PHP 8.0
  SECURITY.md
  src/index.php
  src/setup/routes/setup.php
Labels: breaking-change

#6685 Upgrade System Updates
  src/ChurchCRM/Dashboard/ClassificationDashboardItem.php.php
  src/ChurchCRM/Dashboard/CurrentLocaleMetadata.php
  src/ChurchCRM/Dashboard/DashboardItemInterface.php
  src/ChurchCRM/Dashboard/EventsMenuItems.php
  src/ChurchCRM/Dashboard/SystemUpdateMenuItem.php
  src/ChurchCRM/Service/NewDashboardService.php
  src/ChurchCRM/Service/TaskService.php
  src/ChurchCRM/dto/ChurchCRMReleaseManager.php
  src/ChurchCRM/tasks/LatestReleaseTask.php
  src/Include/Header.php
  src/UpgradeCRM.php
  src/skin/js/CRMJSOM.js
Labels: Installation / Upgrade

#6626 Added missing Fiscal Year to Query View
  src/api/routes/system/system-database.php
  src/mysql/install/Install.sql
  src/mysql/upgrade.json
  src/mysql/upgrade/5.3.0.sql
Labels: bug

#6687 moved from docker-compose to docker compose
  package.json
Labels: development

#6699 Started 5.3.1
  demo/ChurchCRM-Database.sql
  locale/messages.po
  package-lock.json
  package.json
  src/composer.json
  src/mysql/upgrade.json
Labels: build

#6703 Add php types to auth classes
  src/ChurchCRM/Authentication/AuthenticationManager.php
  src/ChurchCRM/Authentication/AuthenticationProviders/APITokenAuthentication.php
  src/ChurchCRM/Authentication/AuthenticationProviders/IAuthenticationProvider.php
  src/ChurchCRM/Authentication/AuthenticationProviders/LocalAuthentication.php
  src/session/index.php
Labels: Code Smell, Authentication / Authorization, php

#6718 fix tax report incorrect args in ChurchCRM\Reports\PdfTaxReport::finishPage()
  src/Reports/TaxReport.php
Labels: bug, Feature: Reports, php

#6719 fix diacritics for directory report
  src/ChurchCRM/Reports/ChurchInfoReport.php
  src/ChurchCRM/Reports/PDF_Directory.php
  src/Reports/CanvassReports.php
  src/Reports/PledgeSummary.php
  src/Reports/TaxReport.php
Labels: bug, Feature: Reports, php

#6710 remove use of extract in CSVImport.php
  src/CSVImport.php
  src/ChurchCRM/data/Countries.php
  src/Include/CountryDropDown.php
Labels: Code Smell, php

#6720 add missing fiscal years for pledge comparison
  src/mysql/install/Install.sql
  src/mysql/upgrade.json
  src/mysql/upgrade/5.3.1.sql
Labels: bug, Platform: Database, Feature: Custom Queries
