Repository ChurchCRM/CRM, pull requests merged in 2023-06, with the labels that each got.

#6495 add dockerfile to python3 and composer fix
  docker/Dockerfile.churchcrm-apache-php8-dev-debian
  src/composer.json
Labels: build

#6492 [Snyk] Upgrade jquery from 3.6.4 to 3.7.0
  package-lock.json
  package.json
Labels: Package Dependencies

#6487 Create ubuntu.sh
  install/ubuntu.sh
Labels: Installation / Upgrade
