Repository ChurchCRM/CRM, pull requests merged in 2023-10, with the labels that each got.

#6529 [Snyk] Upgrade flag-icons from 6.9.5 to 6.11.0
  package-lock.json
  package.json
Labels: Package Dependencies

#6539 Ensure Cypress Test work on 5.0.0
  .gitignore
  cypress/integration/reset/admin.system-reset.js
  cypress/integration/ui/admin/admin.people.spec.js
  cypress/integration/ui/admin/admin.user.password.spec.js
  cypress/integration/ui/finance/finance.family.spec.js
  cypress/integration/ui/guest/guest.family.reg.spec.js
  cypress/integration/ui/standard/standard.cart.spec.js
  cypress/integration/ui/standard/standard.family.spec.js
  cypress/integration/ui/standard/standard.geo.spec.js
  cypress/integration/ui/standard/standard.group.spec.js
  cypress/integration/ui/standard/standard.members.del.spec.js
  cypress/integration/ui/standard/standard.person.new.spec.js
  cypress/integration/ui/standard/standard.user.password.spec.js
  docker/cypress.json
  package.json
  src/ChurchCRM/model/ChurchCRM/Family.php
  src/GroupReports.php
  src/GroupView.php
  src/PersonView.php
  src/SelectDelete.php
  src/api/routes/public/public-register.php
  src/v2/templates/people/family-view.php
Labels: Integration Testing

#6538 DepositSlipEditor spelling
  src/DepositSlipEditor.php
Labels: development

#6540 Fix Event buttons
  src/EventNames.php
  src/ListEvents.php
  src/skin/js/Tooltips.js
Labels: bug

#6542 Build 5.0.1 Package Updates
  demo/ChurchCRM-Database.sql
  package.json
  src/composer.json
  src/mysql/upgrade.json
Labels: build

#6544 Cypress Cpgrade
  .github/workflows/deploy-to-demo.yml
  .gitignore
  cypress/downloads/GroupDirectory-20231021-154905.pdf
  cypress/downloads/GroupDirectory-20231021-155043.pdf
  cypress/e2e/api/private/admin/private.admin.user.settings.spec.js
  cypress/e2e/api/private/standard/private.people.family.verify.spec.js
  cypress/e2e/api/private/standard/private.user.settings.spec.js
  cypress/e2e/api/public/public.data.spec.js
  cypress/e2e/api/public/public.user.spec.js
  cypress/e2e/ui/admin/admin.calendar.spec.js
  cypress/e2e/ui/admin/admin.debug.spec.js
  cypress/e2e/ui/admin/admin.event.spec.js
  cypress/e2e/ui/admin/admin.people.spec.js
  cypress/e2e/ui/admin/admin.reports.spec.js
  cypress/e2e/ui/admin/admin.settings.spec.js
  cypress/e2e/ui/admin/admin.user.password.spec.js
  cypress/e2e/ui/finance/finance.deplosits.spec.js
  cypress/e2e/ui/finance/finance.family.spec.js
  cypress/e2e/ui/guest/guest.family.reg.spec.js
  cypress/e2e/ui/guest/guest.login.errors.spec.js
  cypress/e2e/ui/standard/standard.calendar.spec.js
  cypress/e2e/ui/standard/standard.cart.spec.js
  cypress/e2e/ui/standard/standard.dashbaord.spec.js
  cypress/e2e/ui/standard/standard.events.spec.js
  cypress/e2e/ui/standard/standard.family.spec.js
  cypress/e2e/ui/standard/standard.geo.spec.js
  cypress/e2e/ui/standard/standard.group.spec.js
  cypress/e2e/ui/standard/standard.members.del.spec.js
  cypress/e2e/ui/standard/standard.person.list.spec.js
  cypress/e2e/ui/standard/standard.person.new.spec.js
  cypress/e2e/ui/standard/standard.reports.spec.js
  cypress/e2e/ui/standard/standard.sundayschool.spec.js
  cypress/e2e/ui/standard/standard.user.password.spec.js
  cypress/e2e/ui/standard/standard.user.settings.spec.js
  cypress/e2e/ui/standard/standard.user.spec.js
  cypress/e2e/xReset/admin.system-reset.spec.js
  cypress/support/e2e.js
  docker/cypress.json
  package-lock.json
  package.json
  src/api/routes/system/system-database.php
  src/v2/templates/user/changepassword.php
Labels: Integration Testing, Package Dependencies

#6546 add propel/propel 2.0.0-beta3 to composer.lock
  src/composer.lock
Labels: build

#6549 Add Turkish as a locale
  locale/JSONKeys/tr_TR.json
  src/Include/Header.php
  src/locale/locales.json
  src/locale/textdomain/tr_TR/LC_MESSAGES/messages.mo
  src/locale/textdomain/tr_TR/LC_MESSAGES/messages.po
Labels: Localization

#6559 [rector] migrate to ruleset LevelSetList::UP_TO_PHP_70
  src/ChurchCRM/Bootstrapper.php
  src/ChurchCRM/Service/AppIntegrityService.php
  src/ChurchCRM/Service/FinancialService.php
  src/ChurchCRM/dto/Photo.php
  src/ChurchCRM/model/ChurchCRM/User.php
  src/ChurchCRM/utils/MiscUtils.php
  src/Include/Functions.php
  src/Reports/AdvancedDeposit.php
  src/Reports/ZeroGivers.php
  src/api/routes/system/system-database.php
  src/rector.php
Labels: development, Code Smell

#6563 [rector] migrate to ruleset LevelSetList::UP_TO_PHP_71
  src/ChurchCRM/BackupManager.php
  src/ChurchCRM/Bootstrapper.php
  src/ChurchCRM/Reports/PDF_Attendance.php
  src/ChurchCRM/SQLUtils.php
  src/ChurchCRM/Service/FinancialService.php
  src/ChurchCRM/dto/ChurchCRMReleaseManager.php
  src/ChurchCRM/dto/KioskAssignmentTypes.php
  src/ChurchCRM/dto/Photo.php
  src/ChurchCRM/model/ChurchCRM/Person.php
  src/ChurchCRM/model/ChurchCRM/Token.php
  src/Include/Functions.php
  src/Reports/ClassList.php
  src/Reports/PDFLabel.php
  src/Reports/TaxReport.php
  src/Reports/VotingMembers.php
  src/rector.php
Labels: Code Smell

#6550 apply rector level set list rules to bring codebase to php 7.4
  src/ChurchCRM/Authentication/AuthenticationProviders/LocalAuthentication.php
  src/ChurchCRM/BackupManager.php
  src/ChurchCRM/Bootstrapper.php
  src/ChurchCRM/Config/Menu/MenuItem.php
  src/ChurchCRM/Reports/PDF_AddressReport.php
  src/ChurchCRM/Service/AppIntegrityService.php
  src/ChurchCRM/Service/MailChimpService.php
  src/ChurchCRM/Service/SystemService.php
  src/ChurchCRM/Service/TaskService.php
  src/ChurchCRM/Service/TimelineService.php
  src/ChurchCRM/data/Countries.php
  src/ChurchCRM/data/Country.php
  src/ChurchCRM/dto/ChurchCRMRelease.php
  src/ChurchCRM/dto/ChurchCRMReleaseManager.php
  src/ChurchCRM/dto/PeopleCustomField.php
  src/ChurchCRM/dto/Photo.php
  src/ChurchCRM/dto/Prerequisite.php
  src/ChurchCRM/dto/SystemURLs.php
  src/ChurchCRM/dto/iCal.php
  src/ChurchCRM/model/ChurchCRM/Event.php
  src/ChurchCRM/model/ChurchCRM/Family.php
  src/ChurchCRM/model/ChurchCRM/Person.php
  src/ChurchCRM/tasks/CheckUploadSizeTask.php
  src/ChurchCRM/tasks/LatestReleaseTask.php
  src/ChurchCRM/utils/InputUtils.php
  src/ChurchCRM/utils/LoggerUtils.php
  src/ChurchCRM/utils/PHPToMomentJSConverter.php
  src/Include/Functions.php
  src/Include/slim/error-handler.php
  src/Reports/PhotoBook.php
  src/Reports/ZeroGivers.php
  src/api/index.php
  src/api/routes/cart.php
  src/api/routes/people/people-families.php
  src/api/routes/people/people-persons.php
  src/kiosk/index.php
  src/kiosk/routes/kiosk.php
  src/rector.php
  src/sundayschool/SundaySchoolClassView.php
Labels: build, Code Smell

#6571 Updated Slim MVC to use $app vs $this
  src/api/routes/background.php
  src/api/routes/calendar/calendar.php
  src/api/routes/calendar/events.php
  src/api/routes/cart.php
  src/api/routes/email/mailchimp.php
  src/api/routes/finance/finance-deposits.php
  src/api/routes/finance/finance-payments.php
  src/api/routes/geocoder.php
  src/api/routes/kiosks.php
  src/api/routes/people/people-families.php
  src/api/routes/people/people-family.php
  src/api/routes/people/people-groups.php
  src/api/routes/people/people-person.php
  src/api/routes/people/people-persons.php
  src/api/routes/people/people-properties.php
  src/api/routes/public/public-calendar.php
  src/api/routes/public/public-data.php
  src/api/routes/public/public-register.php
  src/api/routes/public/public-user.php
  src/api/routes/public/public.php
  src/api/routes/system/system-config.php
  src/api/routes/system/system-custom-fields.php
  src/api/routes/system/system-custom-menu.php
  src/api/routes/system/system-database.php
  src/api/routes/system/system-debug.php
  src/api/routes/system/system-issues.php
  src/api/routes/system/system-locale.php
  src/api/routes/system/system-register.php
  src/api/routes/system/system-upgrade.php
  src/api/routes/system/system.php
  src/api/routes/users/user-admin.php
  src/api/routes/users/user-current.php
  src/api/routes/users/user-settings.php
  src/api/routes/users/user.php
  src/external/routes/calendar.php
  src/external/routes/register.php
  src/external/routes/verify.php
  src/v2/routes/admin/admin.php
  src/v2/routes/calendar.php
  src/v2/routes/cart.php
  src/v2/routes/email.php
  src/v2/routes/family.php
  src/v2/routes/people.php
  src/v2/routes/person.php
  src/v2/routes/root.php
  src/v2/routes/user-current.php
  src/v2/routes/user.php
Labels: Code Smell

#6572 PHP Cleanup - DATA / DTO FILES
  src/ChurchCRM/data/Country.php
  src/ChurchCRM/dto/Cart.php
  src/ChurchCRM/dto/ChurchCRMRelease.php
  src/ChurchCRM/dto/ChurchCRMReleaseManager.php
  src/ChurchCRM/dto/Notification.php
  src/ChurchCRM/dto/Notification/UiNotification.php
  src/ChurchCRM/dto/Prerequisite.php
Labels: Code Smell

#6574 Dev class cleanup 5.0.x
  src/ChurchCRM/Reports/PDF_Directory.php
  src/ChurchCRM/data/States.php
  src/SystemDBUpdate.php
Labels: Code Smell

#6554 find and fix various issues found in the codebase
  src/ChurchCRM/Authentication/AuthenticationManager.php
  src/ChurchCRM/BackupManager.php
  src/ChurchCRM/Bootstrapper.php
  src/ChurchCRM/Emails/users/BaseUserEmail.php
  src/ChurchCRM/Search/SearchResultGroup.php
  src/ChurchCRM/Service/AppIntegrityService.php
  src/ChurchCRM/Service/TaskService.php
  src/ChurchCRM/Service/UpgradeService.php
  src/ChurchCRM/data/Country.php
  src/ChurchCRM/dto/ChurchCRMRelease.php
  src/ChurchCRM/model/ChurchCRM/Event.php
  src/ChurchCRM/model/ChurchCRM/Family.php
  src/ChurchCRM/model/ChurchCRM/Person.php
  src/ChurchCRM/model/ChurchCRM/Pledge.php
  src/ChurchCRM/tasks/CheckExecutionTimeTask.php
  src/ChurchCRM/tasks/CheckUploadSizeTask.php
  src/ChurchCRM/tasks/ChurchAddress.php
  src/ChurchCRM/tasks/ChurchNameTask.php
  src/ChurchCRM/tasks/EmailTask.php
  src/ChurchCRM/tasks/HttpsTask.php
  src/ChurchCRM/tasks/IntegrityCheckTask.php
  src/ChurchCRM/tasks/LatestReleaseTask.php
  src/ChurchCRM/tasks/PHPPendingDeprecationVersionCheckTask.php
  src/ChurchCRM/tasks/PHPZipArchiveCheckTask.php
  src/ChurchCRM/tasks/PersonClassificationDataCheck.php
  src/ChurchCRM/tasks/PersonGenderDataCheck.php
  src/ChurchCRM/tasks/PersonRoleDataCheck.php
  src/ChurchCRM/tasks/PrerequisiteCheckTask.php
  src/ChurchCRM/tasks/RegisteredTask.php
  src/ChurchCRM/tasks/SecretsConfigurationCheckTask.php
  src/ChurchCRM/tasks/UnsupportedDepositCheck.php
  src/ChurchCRM/tasks/UpdateFamilyCoordinatesTask.php
  src/ChurchCRM/tasks/iTask.php
  src/ChurchCRM/utils/MiscUtils.php
  src/FindFundRaiser.php
  src/Include/Config.php.example
  src/Reports/ConfirmReport.php
  src/Reports/ConfirmReportEmail.php
  src/Reports/DirectoryReport.php
  src/Reports/EnvelopeReport.php
  src/Reports/FRCatalog.php
  src/Reports/FamilyPledgeSummary.php
  src/Reports/PDFLabel.php
  src/SystemDBUpdate.php
  src/api/routes/people/people-family.php
  src/api/routes/system/system-database.php
  src/api/routes/system/system-issues.php
  src/composer.json
  src/external/routes/verify.php
Labels: Code Smell

#6578 Setup working on PHP 8
  src/ChurchCRM/Bootstrapper.php
  src/setup/routes/setup.php
Labels: bug

#6577 more minor code cleanup
  src/ChurchCRM/Authentication/AuthenticationManager.php
  src/ChurchCRM/Reports/PDF_CertificatesReport.php
  src/ChurchCRM/Slim/Middleware/Request/UserAPIMiddleware.php
  src/ChurchCRM/data/States.php
  src/Reports/FRBidSheets.php
  src/Reports/PDFLabel.php
Labels: Code Smell

#6573 Test Build branches - start test docker and test
  .github/workflows/build-test.yml
  cypress/e2e/xReset/admin.system-reset.spec.js
  docker/Dockerfile.churchcrm-apache-php8-test-debian
  docker/docker-compose.dev-php8-apache.yaml
  docker/docker-compose.test-php8-apache.gh-actions.yaml
  docker/docker-compose.test-php8-apache.yaml
  package.json
Labels: build, Integration Testing

#6579 Fixed Person / Family photo & thumbnail API
  src/ChurchCRM/utils/MiscUtils.php
  src/api/routes/people/people-family.php
  src/api/routes/people/people-person.php
Labels: bug

#6580 Integration Test Reorder
  cypress/e2e/ui/events/standard.calendar.spec.js
  cypress/e2e/ui/events/standard.events.spec.js
  cypress/e2e/ui/groups/standard.group.spec.js
  cypress/e2e/ui/groups/standard.sundayschool.spec.js
  cypress/e2e/ui/people/standard.family.spec.js
  cypress/e2e/ui/people/standard.members.del.spec.js
  cypress/e2e/ui/people/standard.person.list.spec.js
  cypress/e2e/ui/people/standard.person.new.spec.js
  cypress/e2e/ui/reports/standard.reports.spec.js
  cypress/e2e/ui/user/standard.user.password.spec.js
  cypress/e2e/ui/user/standard.user.settings.spec.js
  cypress/e2e/ui/user/standard.user.spec.js
Labels: Integration Testing

#6576 Remove php 7 from scripts
  docker/Dockerfile.churchcrm-apache-php7-test-debian
  docker/docker-compose.test-php7-apache.yaml
  install/ubuntu.sh
  package.json
Labels: build, development, Integration Testing, Installation / Upgrade

#6581 Bug fixes - User Setting / View Person / CVS Import
  src/CSVImport.php
  src/Include/Footer.php
  src/PersonView.php
  src/UserList.php
  src/skin/js/MemberView.js
  src/skin/js/user.js
  src/v2/templates/user/user.php
Labels: bug, UI

#6585 Removed Intelligent Search Technolgy as a tool
  locale/messages.po
  src/ChurchCRM/ISTAddressLookup.php
  src/ChurchCRM/dto/SystemConfig.php
  src/ChurchCRM/model/ChurchCRM/User.php
  src/PeopleDashboard.php
  src/Reports/USISTAddressReport.php
  src/USISTAddressVerification.php
  src/mysql/install/Install.sql
Labels: bug, Code Smell

#6586 Test/ensure load top pages
  cypress/e2e/ui/email/standard.email.spec.js
  cypress/e2e/ui/groups/standard.group.spec.js
  cypress/e2e/ui/main.dashbaord.spec.js
  cypress/e2e/ui/people/standard.cart.spec.js
  cypress/e2e/ui/people/standard.person.list.spec.js
  cypress/e2e/ui/people/standard.person.tools.spec.js
  cypress/e2e/ui/standard/standard.geo.spec.js
Labels: Integration Testing

#6594 More https corrections
  .editorconfig
  README.md
  package.json
  postman/Collections/Private API.postman_collection.json
  scripts/update-demo-site.php
  src/Include/FooterNotLoggedIn.php
  src/PersonView.php
  src/api/routes/system/system-register.php
  src/bin/google-map/GoogleMap.php
  src/composer.json
  src/setup/templates/setup-error.php
Labels: Documentation, Code Smell

#6597 Using Docker Mail Server
  demo/ChurchCRM-Database.sql
  docker/docker-compose.test-php8-apache.yaml
Labels: Integration Testing

#6588 update various npm dependencies
  package-lock.json
  package.json
  react/components/Events/EventPropertiesEditor.tsx
Labels: Package Dependencies

#6589 add logs to upgrade flow to make it easier to triage errors
  src/ChurchCRM/FileSystemUtils.php
  src/ChurchCRM/dto/ChurchCRMReleaseManager.php
Labels: Installation / Upgrade

#6598 Remove permissions for usAddressVerification
  src/mysql/install/Install.sql
Labels: Code Smell

#6601 Ckeditor
  Gruntfile.js
  package-lock.json
  package.json
Labels: UI, Package Dependencies
